# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=false
org.gradle.daemon=true

mc_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_version=21.1.224
neo_version_range=[21.1.1,)
minecraft_version_range=[1.21,1.22)

mod_id=tsuki
mod_name=Tsuki
mod_license=MIT
mod_version=1.5.0-dev
mod_group_id=cn.mcmod.tsuki
mod_authors=Polaris_Light, Syameimaru Zheng, Bagu_chan
mod_description=A mod that mix Bamboo, WA and MapleTree.\nThis mod is full of Japanese style, Teishoku, sushi, and lots of foods.\nNew battle styles with your katana and kodachi, Cooking with campfire and cooking pot.\nNew illager with his katana spawn in Bamboo forest and maple forest!\nNew dress: Kimono, yukata and Haori.

jei_version=19.27.0.340
emi_version=1.1.22+1.21.1
geckolib_version=4.8.2
