package ecru.MapleTree;

import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.common.config.Property;

public class loadConfiguration {
    public void load(FMLPreInitializationEvent event) {
        Configuration cfg = new Configuration(event.getSuggestedConfigurationFile());
        try {
            try {
                cfg.load();
                cfg.addCustomCategoryComment("Basic", "   ");
                Property data = cfg.get("basic", "TreeDeleted", false);
                data.comment = "A tree is deleted at the time of loading of a chunk. (true/false)\nPlease change to TRUE only at the time of deletion. ";
                mod_ecru_MapleTree.TreeDeleted = data.getBoolean(false);
                Property data2 = cfg.get("basic", "FallenLeavesParticles", false);
                data2.comment = "Fallen leaves particles are displayed. (true/false)";
                mod_ecru_MapleTree.FallenLeavesParticles = data2.getBoolean(false);
                Property data3 = cfg.get("basic", "GrassDropsSeeds", true);
                data3.comment = "Grass drops a seeds. (true/false)";
                mod_ecru_MapleTree.GrassDropsSeeds = data3.getBoolean(true);
                Property data4 = cfg.get("basic", "SmallStairsSpaceFilled", false);
                data4.comment = "The space of stairs is buried. (true/false)";
                mod_ecru_MapleTree.MiniStairsLong = data4.getBoolean(false);
                Property data5 = cfg.get("basic", "FallenLeavesDropped", true);
                data5.comment = "Fallen leaves are dropped at the time of growth of a tree. (true/false)";
                mod_ecru_MapleTree.FallenLeavesDropped = data5.getBoolean(true);
                Property data6 = cfg.get("basic", "FallenLeavesColorRed", false);
                data6.comment = "The color of fallen leaves is fixed to red. (true/false)";
                mod_ecru_MapleTree.FallenLeavesColorRed = data6.getBoolean(false);
                Property data7 = cfg.get("basic", "GraphicsLevel", 2);
                data7.comment = "Graphics Level (0-2)   0:FANCY fixation   1:FAST fixation   2:Video Settings";
                mod_ecru_MapleTree.GraphicsLevel = data7.getInt();
                Property data8 = cfg.get("basic", "HelpTips", true);
                data8.comment = "Display help tips.(startup) (true/false)";
                mod_ecru_MapleTree.helpTip = data8.getBoolean(true);
                Property data9 = cfg.get("basic", "helpTip_posY", 60);
                data9.comment = "Indication point of the Y coordinate.(percent) 0-100% (default:60) ";
                mod_ecru_MapleTree.helpTip_posY = data9.getInt();
                mod_ecru_MapleTree.EnvironmentSounds = cfg.getFloat("EnvironmentSounds", "basic", 0.0f, 0.0f, 1.0f, "Environment Sounds volume ");
                Property data10 = cfg.get("basic", "mushroomParticle", true);
                data10.comment = "Display mushroom particle (true/false)";
                mod_ecru_MapleTree.mushroomParticle = data10.getBoolean(true);
                cfg.addCustomCategoryComment("generation", "   ");
                Property data11 = cfg.get("generation", "GenerationRate", 10);
                data11.comment = "Maple tree generation rate on hills. (0-20)";
                mod_ecru_MapleTree.GenerationRate = data11.getInt();
                Property data12 = cfg.get("generation", "generationOnForest", true);
                data12.comment = "Maple tree generation on forest. (true/false) ";
                mod_ecru_MapleTree.GenerationForest = data12.getBoolean(true);
                Property data13 = cfg.get("generation", "GenerateOre", true);
                data13.comment = "Generate ore. (true/false)";
                mod_ecru_MapleTree.GenerateOre = data13.getBoolean(true);
                Property data14 = cfg.get("generation", "SpiceTreeGenerationOnForest", true);
                data14.comment = "A tree of spice is generation in a forest and the savanna. (true/false) ";
                mod_ecru_MapleTree.GenerationSpiceTree = data14.getBoolean(true);
                cfg.addCustomCategoryComment("decoration", "Decoration block");
                Property data15 = cfg.get("decoration", "DecorationBlockTexture1", 0);
                data15.comment = "Setect texture WOOD         0:mod  /  Vanilla 1:Wooden Planks(Oak)  2:Wooden Planks(Spruce)  3:Wooden Planks(Birch) 4:Wooden Planks(Jungle) 5:Log(Oak)";
                mod_ecru_MapleTree.decoTextureID1 = data15.getInt();
                Property data16 = cfg.get("decoration", "DecorationBlockTexture2", 0);
                data16.comment = "Setect texture STONE        0:mod  /  Vanilla 1:Stone  2:Stone Bricks  3:Bricks  4:Sstone Brick mossy  5:quartz block chiseled  6:quartz block lines";
                mod_ecru_MapleTree.decoTextureID2 = data16.getInt();
                Property data17 = cfg.get("decoration", "DecorationBlockTexture3", 0);
                data17.comment = "Setect texture OTHER        0:mod  /  Vanilla 1:Block of Iron  2:Sandstone  \n                                        WOOL  3:white 4:Orange 5:Magenta 6:Light Blue 7:Yellow 8:Lime 9:Pink 10:Gray 11:Light Gray \n                                             12:Cyan 13:Purple 14:Blue 15:Brown 16:Green 17:Red 18:Black \n                                             19:Sandstone carved  20:Sandstone smooth";
                mod_ecru_MapleTree.decoTextureID3 = data17.getInt();
                cfg.addCustomCategoryComment("lighthouse-light", "Lighthouse illumination");
                Property data18 = cfg.get("lighthouse-light", "LighthouseIlluminationColor", "FFFF00");
                data18.comment = "Ray of light [Color  FORMAT:RRGGBB]  (default:FFFF00)";
                mod_ecru_MapleTree.LighthouseIlluminationColorStr = data18.getString();
                Property data19 = cfg.get("lighthouse-light", "LighthouseIlluminationLength", 30);
                data19.comment = "Ray of light [Light length 5-30]  (default:30)";
                mod_ecru_MapleTree.LighthouseIlluminationLength = data19.getInt();
                Property data20 = cfg.get("lighthouse-light", "LighthouseIlluminationWidth", 6);
                data20.comment = "Ray of light [Light width 1-10]  (default:6)";
                mod_ecru_MapleTree.LighthouseIlluminationWidth = data20.getInt();
                Property data21 = cfg.get("lighthouse-light", "LighthouseIlluminationTransparency", 255);
                data21.comment = "Ray of light [Light Transparency 30-255]  (default:255)";
                mod_ecru_MapleTree.LighthouseIlluminationTransparency = data21.getInt();
                Property data22 = cfg.get("lighthouse-light", "LighthouseIlluminationViewMode", 1);
                data22.comment = "Ray of light [Light view mode 0 or 1]  (default:1)";
                mod_ecru_MapleTree.LighthouseIlluminationViewMode = data22.getInt();
                Property data23 = cfg.get("lighthouse-light", "LighthouseIlluminationPolygonCount", 5);
                data23.comment = "Ray of light [Light Polygon count 3-10]  (default:5)";
                mod_ecru_MapleTree.LighthouseIlluminationPolygonCount = data23.getInt();
                cfg.addCustomCategoryComment("s-light", "S-Light");
                Property data24 = cfg.get("s-light", "SLightColor", "FFFF00");
                data24.comment = "Ray of light [S-Light Color  FORMAT:RRGGBB]  (default:FFFF00)";
                mod_ecru_MapleTree.SLightColorStr = data24.getString();
                Property data25 = cfg.get("s-light", "SLightLength", 12);
                data25.comment = "Ray of light [S-Light length 5-30]  (default:12)";
                mod_ecru_MapleTree.SLightLength = data25.getInt();
                Property data26 = cfg.get("s-light", "SLightWidth", 3);
                data26.comment = "Ray of light [S-Light width 1-10]  (default:3)";
                mod_ecru_MapleTree.SLightWidth = data26.getInt();
                Property data27 = cfg.get("s-light", "SLightTransparency", 255);
                data27.comment = "Ray of light [S-Light Transparency 30-255]  (default:255)";
                mod_ecru_MapleTree.SLightTransparency = data27.getInt();
                cfg.addCustomCategoryComment("mob", "MOMIJI");
                mod_ecru_MapleTree.MomijiSounds = cfg.getFloat("MomijiSounds", "mob", 0.5f, 0.0f, 1.0f, "Momiji Sounds volume ");
                Property data28 = cfg.get("mob", "excludeSeeds", mod_ecru_MapleTree.defaultExcludeSeeds);
                data28.comment = "excludeSeeds";
                mod_ecru_MapleTree.excludeSeedsList = data28.getString();
                Property data29 = cfg.get("mob", "plantSeedRandom", false);
                data29.comment = "I plant a seed at random. (true/false)";
                mod_ecru_MapleTree.plantSeedRandom = data29.getBoolean(false);
                Property data30 = cfg.get("mob", "momijiActivityField", 18);
                data30.comment = "momiji Activity field (the radius) [range 10 - 22   default : 18]";
                mod_ecru_MapleTree.momijiActivityField = data30.getInt();
                Property data31 = cfg.get("mob", "momijiDespawnTime", 2);
                data31.comment = "momiji despawn time (minute) [range 2 - 20   default : 2]";
                mod_ecru_MapleTree.momijiDespawnTime = data31.getInt();
                Property data32 = cfg.get("mob", "momijiSpawnRate", 20);
                data32.comment = "momiji Spawn rate [range 0 - 50   default : 20]";
                mod_ecru_MapleTree.momijiSpawnRate = data32.getInt();
                Property data33 = cfg.get("mob", "momijiLightTexture", true);
                data33.comment = "enable a momiji light texture (true/false)";
                mod_ecru_MapleTree.momijiLightTexture = data33.getBoolean(true);
                Property data34 = cfg.get("mob", "momijiBlinkTexture", true);
                data34.comment = "enable a momiji blink texture (true/false)";
                mod_ecru_MapleTree.momijiBlinkTexture = data34.getBoolean(true);
                Property data35 = cfg.get("mob", "addLogList", "");
                data35.comment = "List of planting log and sapling [FORMAT  logname;meta;saplingname;meta,....  ]";
                mod_ecru_MapleTree.addLogList = data35.getString();
                Property data36 = cfg.get("mob", "LogBlockFellingMAX", 200);
                data36.comment = "The maximum number of Log block felling [range 1 - 3000  default : 200]";
                mod_ecru_MapleTree.LogBlockFellingMAX = data36.getInt();
                Property data37 = cfg.get("mob", "momijiCutAllMode", 0);
                data37.comment = "MODE 0 : Even if the durability disappears, I destroy it till the last. \nMODE 1 : If the durability disappears, it is finished.\n[default 0]";
                mod_ecru_MapleTree.momijiCutAllMode = data37.getInt();
                Property data38 = cfg.get("mob", "registeredSeedPlant", true);
                data38.comment = "Harvest time,I plant a seed registered with the crops. (true/false)";
                mod_ecru_MapleTree.registeredSeedPlant = data38.getBoolean(true);
                Property data39 = cfg.get("mob", "magicalcropsEnable", true);
                data39.comment = "enable a harvest of the (Magical crops) (true/false)";
                mod_ecru_MapleTree.magicalcropsEnable = data39.getBoolean(true);
                Property data40 = cfg.get("mob", "MomijiEntityId", -1);
                data40.comment = "Momiji entityId [-1:auto]";
                mod_ecru_MapleTree.entityId = data40.getInt();
                Property data41 = cfg.get("mob", "walkingFrequency", 30);
                data41.comment = "The frequency of random walking [little 1 - 100 much    default : 30 ]";
                mod_ecru_MapleTree.walkingFrequency = data41.getInt();
                Property data42 = cfg.get("mob", "harvestLeaves", true);
                data42.comment = "When felling a tree, I harvest the leaf at the same time. (true/false)";
                mod_ecru_MapleTree.harvestLeaves = data42.getBoolean(true);
                cfg.addCustomCategoryComment("villager", "A villager and barter.");
                Property data43 = cfg.get("villager", "villagerBarter_GrapeSeeds", true);
                data43.comment = "Gold ingot <-> Grape seeds";
                mod_ecru_MapleTree.villagerBarter_GrapeSeeds = data43.getBoolean(true);
                Property data44 = cfg.get("villager", "villagerBarter_PeppercornBunch", true);
                data44.comment = "Diamond  <-> Peppercorn bunch";
                mod_ecru_MapleTree.villagerBarter_PeppercornBunch = data44.getBoolean(true);
                Property data45 = cfg.get("villager", "villagerBarter_SoySauce", true);
                data45.comment = "Wheat <-> Soy sauce";
                mod_ecru_MapleTree.villagerBarter_SoySauce = data45.getBoolean(true);
                Property data46 = cfg.get("villager", "villagerBarter_Miso", true);
                data46.comment = "Wheat <-> Miso";
                mod_ecru_MapleTree.villagerBarter_Miso = data46.getBoolean(true);
                Property data47 = cfg.get("villager", "villagerBarter_IronIngot", true);
                data47.comment = "Wine <-> Iron ingot";
                mod_ecru_MapleTree.villagerBarter_IronIngot = data47.getBoolean(true);
                Property data48 = cfg.get("villager", "villagerBarter_GoldIngot", true);
                data48.comment = "Wine <-> Gold ingot";
                mod_ecru_MapleTree.villagerBarter_GoldIngot = data48.getBoolean(true);
                Property data49 = cfg.get("villager", "villagerBarter_MomenTofu", true);
                data49.comment = "Momen Tofu <-> Gold ingot";
                mod_ecru_MapleTree.villagerBarter_MomenTofu = data49.getBoolean(true);
                Property data50 = cfg.get("villager", "villagerBarter_Scallion", true);
                data50.comment = "Scallion <-> Gold ingot";
                mod_ecru_MapleTree.villagerBarter_Scallion = data50.getBoolean(true);
                Property data51 = cfg.get("villager", "villagerBarter_KelpSporophyte", true);
                data51.comment = "Kelp Sporophyte <-> Gold ingot";
                mod_ecru_MapleTree.villagerBarter_KelpSporophyte = data51.getBoolean(true);
                Property data52 = cfg.get("villager", "villagerBarter_Compost", true);
                data52.comment = "Emerald block <-> Legendary fallen leaves";
                mod_ecru_MapleTree.villagerBarter_Compost = data52.getBoolean(true);
                cfg.addCustomCategoryComment("recipe", "Relief");
                Property data53 = cfg.get("recipe", "spiceReliefRecipe", false);
                data53.comment = "A recipe of help is opened. [ default : false ]";
                mod_ecru_MapleTree.spiceReliefRecipe = data53.getBoolean(false);
                mod_ecru_MapleTree.decorationNormalBlock = false;
                mod_ecru_MapleTree.proxy.init();
                cfg.save();
            } catch (Exception e) {
                System.out.println("========== Maple tree config error ==========");
                cfg.save();
            }
        } catch (Throwable th) {
            cfg.save();
            throw th;
        }
    }
}
