package ecru.MapleTree;

import cpw.mods.fml.common.registry.GameRegistry;
import ecru.MapleTree.block.ecru_BlockBiofuelPD;
import ecru.MapleTree.block.ecru_BlockCauldron;
import ecru.MapleTree.block.ecru_BlockChestnutsBurrs;
import ecru.MapleTree.block.ecru_BlockCompost;
import ecru.MapleTree.block.ecru_BlockCookPot;
import ecru.MapleTree.block.ecru_BlockCropsAzuki;
import ecru.MapleTree.block.ecru_BlockCropsCabbage;
import ecru.MapleTree.block.ecru_BlockCropsJapaneseRadish;
import ecru.MapleTree.block.ecru_BlockCropsRapeseed;
import ecru.MapleTree.block.ecru_BlockCropsSoba;
import ecru.MapleTree.block.ecru_BlockCropsStickyRice;
import ecru.MapleTree.block.ecru_BlockDecoration1;
import ecru.MapleTree.block.ecru_BlockDecoration2;
import ecru.MapleTree.block.ecru_BlockDecoration3;
import ecru.MapleTree.block.ecru_BlockDriedPersimmon;
import ecru.MapleTree.block.ecru_BlockEggplant;
import ecru.MapleTree.block.ecru_BlockEngine;
import ecru.MapleTree.block.ecru_BlockFallenLeaves;
import ecru.MapleTree.block.ecru_BlockFallenLeavesFire;
import ecru.MapleTree.block.ecru_BlockFountain;
import ecru.MapleTree.block.ecru_BlockGatherItems;
import ecru.MapleTree.block.ecru_BlockGrainDryer;
import ecru.MapleTree.block.ecru_BlockGrainHopper;
import ecru.MapleTree.block.ecru_BlockGrape;
import ecru.MapleTree.block.ecru_BlockGrapeTub;
import ecru.MapleTree.block.ecru_BlockHumanPowerDrive;
import ecru.MapleTree.block.ecru_BlockKelp;
import ecru.MapleTree.block.ecru_BlockLeafFence;
import ecru.MapleTree.block.ecru_BlockLighthouseIllumination;
import ecru.MapleTree.block.ecru_BlockMapleLeaves;
import ecru.MapleTree.block.ecru_BlockMapleSapling;
import ecru.MapleTree.block.ecru_BlockMapleWood;
import ecru.MapleTree.block.ecru_BlockMapleWoodSyrup;
import ecru.MapleTree.block.ecru_BlockMarble;
import ecru.MapleTree.block.ecru_BlockMarbleJewel;
import ecru.MapleTree.block.ecru_BlockMiniStairs;
import ecru.MapleTree.block.ecru_BlockMortar;
import ecru.MapleTree.block.ecru_BlockOnion;
import ecru.MapleTree.block.ecru_BlockOreBlobk;
import ecru.MapleTree.block.ecru_BlockOreFlower;
import ecru.MapleTree.block.ecru_BlockOreFlowerGold;
import ecru.MapleTree.block.ecru_BlockOreFlowerIron;
import ecru.MapleTree.block.ecru_BlockOreFlowerMarble;
import ecru.MapleTree.block.ecru_BlockPepper;
import ecru.MapleTree.block.ecru_BlockPersimmon;
import ecru.MapleTree.block.ecru_BlockPersimmonLeaves;
import ecru.MapleTree.block.ecru_BlockPersimmonSapling;
import ecru.MapleTree.block.ecru_BlockPersimmonWood;
import ecru.MapleTree.block.ecru_BlockPetal;
import ecru.MapleTree.block.ecru_BlockPlanter;
import ecru.MapleTree.block.ecru_BlockPowerShaft;
import ecru.MapleTree.block.ecru_BlockPowerShaftGear;
import ecru.MapleTree.block.ecru_BlockSLight;
import ecru.MapleTree.block.ecru_BlockSLight2;
import ecru.MapleTree.block.ecru_BlockSpice;
import ecru.MapleTree.block.ecru_BlockSpile;
import ecru.MapleTree.block.ecru_BlockSprinkler;
import ecru.MapleTree.block.ecru_BlockStoneMortar;
import ecru.MapleTree.block.ecru_BlockSunDryingNet;
import ecru.MapleTree.block.ecru_BlockSunFlower;
import ecru.MapleTree.block.ecru_BlockTeuchiUdon;
import ecru.MapleTree.block.ecru_BlockTomato;
import ecru.MapleTree.block.ecru_BlockVanilla;
import ecru.MapleTree.block.ecru_BlockWhiteFence;
import ecru.MapleTree.block.ecru_BlockWineBarrel;
import ecru.MapleTree.block.ecru_BlockWineFaucet;
import ecru.MapleTree.block.spice.ecru_BlockAllSpiceLeaves;
import ecru.MapleTree.block.spice.ecru_BlockAllspiceThinPlanks;
import ecru.MapleTree.block.spice.ecru_BlockAllspiceWood;
import ecru.MapleTree.block.spice.ecru_BlockCinnamonLeaves;
import ecru.MapleTree.block.spice.ecru_BlockCinnamonThinPlanks;
import ecru.MapleTree.block.spice.ecru_BlockCinnamonWood;
import ecru.MapleTree.block.spice.ecru_BlockCloveLeaves;
import ecru.MapleTree.block.spice.ecru_BlockCloveThinPlanks;
import ecru.MapleTree.block.spice.ecru_BlockCloveWood;
import ecru.MapleTree.block.spice.ecru_BlockCropsCardamon;
import ecru.MapleTree.block.spice.ecru_BlockCropsChili_pepper;
import ecru.MapleTree.block.spice.ecru_BlockCropsCoriander;
import ecru.MapleTree.block.spice.ecru_BlockCropsCumin;
import ecru.MapleTree.block.spice.ecru_BlockCropsFennel;
import ecru.MapleTree.block.spice.ecru_BlockCropsTurmeric;
import ecru.MapleTree.block.spice.ecru_BlockNutmegLeaves;
import ecru.MapleTree.block.spice.ecru_BlockNutmegThinPlanks;
import ecru.MapleTree.block.spice.ecru_BlockNutmegWood;
import ecru.MapleTree.block.spice.ecru_BlockStarAniseThinPlanks;
import ecru.MapleTree.block.spice.ecru_BlockStar_aniseLeaves;
import ecru.MapleTree.block.spice.ecru_BlockStar_aniseWood;
import ecru.MapleTree.block.spice.ecru_BlockThinSapling;
import ecru.MapleTree.item.ecru_ItemAllSpiceLeaves;
import ecru.MapleTree.item.ecru_ItemAllspiceThinPlanks;
import ecru.MapleTree.item.ecru_ItemAllspiceWood;
import ecru.MapleTree.item.ecru_ItemBiofuelPD;
import ecru.MapleTree.item.ecru_ItemBlock;
import ecru.MapleTree.item.ecru_ItemCabbage;
import ecru.MapleTree.item.ecru_ItemCauldron;
import ecru.MapleTree.item.ecru_ItemChestnutsBurrs;
import ecru.MapleTree.item.ecru_ItemCinnamonLeaves;
import ecru.MapleTree.item.ecru_ItemCinnamonThinPlanks;
import ecru.MapleTree.item.ecru_ItemCinnamonWood;
import ecru.MapleTree.item.ecru_ItemCloveLeaves;
import ecru.MapleTree.item.ecru_ItemCloveThinPlanks;
import ecru.MapleTree.item.ecru_ItemCloveWood;
import ecru.MapleTree.item.ecru_ItemDecoration1;
import ecru.MapleTree.item.ecru_ItemDecoration2;
import ecru.MapleTree.item.ecru_ItemDecoration3;
import ecru.MapleTree.item.ecru_ItemDriedPersimmons;
import ecru.MapleTree.item.ecru_ItemFallenLeaves;
import ecru.MapleTree.item.ecru_ItemFallenLeavesFire;
import ecru.MapleTree.item.ecru_ItemFountain;
import ecru.MapleTree.item.ecru_ItemGrapePergola;
import ecru.MapleTree.item.ecru_ItemGrapeTub;
import ecru.MapleTree.item.ecru_ItemHumanPowerDrive;
import ecru.MapleTree.item.ecru_ItemLeafFence;
import ecru.MapleTree.item.ecru_ItemMapleLeaves;
import ecru.MapleTree.item.ecru_ItemMapleSapling;
import ecru.MapleTree.item.ecru_ItemMapleWood;
import ecru.MapleTree.item.ecru_ItemMapleWoodSyrup;
import ecru.MapleTree.item.ecru_ItemMarble;
import ecru.MapleTree.item.ecru_ItemMarbleJewel0;
import ecru.MapleTree.item.ecru_ItemMarbleJewel1;
import ecru.MapleTree.item.ecru_ItemMarbleJewel2;
import ecru.MapleTree.item.ecru_ItemMarbleJewel3;
import ecru.MapleTree.item.ecru_ItemMarbleJewel4;
import ecru.MapleTree.item.ecru_ItemMarbleJewel5;
import ecru.MapleTree.item.ecru_ItemMarbleJewel6;
import ecru.MapleTree.item.ecru_ItemMarbleJewel7;
import ecru.MapleTree.item.ecru_ItemMiniStairs1;
import ecru.MapleTree.item.ecru_ItemMiniStairs2;
import ecru.MapleTree.item.ecru_ItemMiniStairs3;
import ecru.MapleTree.item.ecru_ItemMiniStairs4;
import ecru.MapleTree.item.ecru_ItemMortar;
import ecru.MapleTree.item.ecru_ItemNutmegLeaves;
import ecru.MapleTree.item.ecru_ItemNutmegThinPlanks;
import ecru.MapleTree.item.ecru_ItemNutmegWood;
import ecru.MapleTree.item.ecru_ItemOreBlock;
import ecru.MapleTree.item.ecru_ItemOreFlowerGold;
import ecru.MapleTree.item.ecru_ItemOreFlowerIron;
import ecru.MapleTree.item.ecru_ItemOreFlowerMarble;
import ecru.MapleTree.item.ecru_ItemOreFlowerRed;
import ecru.MapleTree.item.ecru_ItemPepperSplint;
import ecru.MapleTree.item.ecru_ItemPersimmon;
import ecru.MapleTree.item.ecru_ItemPersimmonLeaves;
import ecru.MapleTree.item.ecru_ItemPersimmonSapling;
import ecru.MapleTree.item.ecru_ItemPersimmonWood;
import ecru.MapleTree.item.ecru_ItemPetal;
import ecru.MapleTree.item.ecru_ItemPowerShaft;
import ecru.MapleTree.item.ecru_ItemPowerShaftGear;
import ecru.MapleTree.item.ecru_ItemSLight;
import ecru.MapleTree.item.ecru_ItemSLight2;
import ecru.MapleTree.item.ecru_ItemSpice;
import ecru.MapleTree.item.ecru_ItemSpile;
import ecru.MapleTree.item.ecru_ItemSprinkler;
import ecru.MapleTree.item.ecru_ItemStarAniseThinPlanks;
import ecru.MapleTree.item.ecru_ItemStar_aniseLeaves;
import ecru.MapleTree.item.ecru_ItemStar_aniseWood;
import ecru.MapleTree.item.ecru_ItemSunFlower;
import ecru.MapleTree.item.ecru_ItemTeuchiSoba;
import ecru.MapleTree.item.ecru_ItemTeuchiUdon;
import ecru.MapleTree.item.ecru_ItemThinSapling;
import ecru.MapleTree.item.ecru_ItemVanillaSplint;
import ecru.MapleTree.item.ecru_ItemWhiteFence;
import ecru.MapleTree.item.ecru_ItemWineBarrel;
import ecru.MapleTree.item.ecru_ItemWineFaucet;
import net.minecraft.block.Block;
import net.minecraft.item.ItemBlock;

public class mapleTreeRegistryBlock {
    public void registry() {
        mod_ecru_MapleTree.blockMapleSapling = new ecru_BlockMapleSapling().func_149672_a(Block.field_149779_h);
        mod_ecru_MapleTree.blockMapleSapling.func_149711_c(0.2f).func_149713_g(1).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:MapleSapling");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMapleSapling, ecru_ItemMapleSapling.class, "ecru_BlockMapleSapling");
        mod_ecru_MapleTree.blockMapleLeaves = new ecru_BlockMapleLeaves();
        mod_ecru_MapleTree.blockMapleLeaves.func_149711_c(0.2f).func_149713_g(1).func_149672_a(Block.field_149779_h).func_149715_a(0.0f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:MapleLeaves");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMapleLeaves, ecru_ItemMapleLeaves.class, "ecru_BlockMapleLeaves");
        mod_ecru_MapleTree.blockFallenLeaves = new ecru_BlockFallenLeaves();
        mod_ecru_MapleTree.blockFallenLeaves.func_149711_c(0.05f).func_149713_g(0).func_149672_a(Block.field_149779_h).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:FallenLeaves");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockFallenLeaves, ecru_ItemFallenLeaves.class, "ecru_BlockFallenLeaves");
        mod_ecru_MapleTree.blockLeafFence = new ecru_BlockLeafFence();
        mod_ecru_MapleTree.blockLeafFence.func_149711_c(0.1f).func_149713_g(0).func_149672_a(Block.field_149779_h).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:LeafFence");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockLeafFence, ecru_ItemLeafFence.class, "ecru_BlockLeafFence");
        mod_ecru_MapleTree.blockFallenLeavesFire = new ecru_BlockFallenLeavesFire();
        mod_ecru_MapleTree.blockFallenLeavesFire.func_149711_c(0.05f).func_149713_g(0).func_149672_a(Block.field_149779_h).func_149715_a(1.0f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:Bonfire");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockFallenLeavesFire, ecru_ItemFallenLeavesFire.class, "ecru_BlockFallenLeavesFire");
        mod_ecru_MapleTree.blockMapleWood = new ecru_BlockMapleWood();
        mod_ecru_MapleTree.blockMapleWood.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:MapleWood");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMapleWood, ecru_ItemMapleWood.class, "ecru_BlockMapleWood");
        mod_ecru_MapleTree.blockMapleWoodSyrup = new ecru_BlockMapleWoodSyrup();
        mod_ecru_MapleTree.blockMapleWoodSyrup.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:MapleWoodSyrup");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMapleWoodSyrup, ecru_ItemMapleWoodSyrup.class, "ecru_BlockMapleWoodSyrup");
        mod_ecru_MapleTree.blockPersimmonLeaves = new ecru_BlockPersimmonLeaves();
        mod_ecru_MapleTree.blockPersimmonLeaves.func_149711_c(0.2f).func_149713_g(1).func_149672_a(Block.field_149779_h).func_149715_a(0.0f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:PersimmonLeaves");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPersimmonLeaves, ecru_ItemPersimmonLeaves.class, "PersimmonLeaves");
        mod_ecru_MapleTree.blockPersimmonWood = new ecru_BlockPersimmonWood();
        mod_ecru_MapleTree.blockPersimmonWood.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:PersimmonWood");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPersimmonWood, ecru_ItemPersimmonWood.class, "PersimmonWood");
        mod_ecru_MapleTree.blockPersimmonSapling = new ecru_BlockPersimmonSapling().func_149672_a(Block.field_149779_h);
        mod_ecru_MapleTree.blockPersimmonSapling.func_149711_c(0.2f).func_149713_g(1).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:PersimmonSapling");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPersimmonSapling, ecru_ItemPersimmonSapling.class, "PersimmonSapling");
        mod_ecru_MapleTree.blockPersimmon = new ecru_BlockPersimmon().func_149672_a(Block.field_149779_h);
        mod_ecru_MapleTree.blockPersimmon.func_149711_c(0.2f).func_149713_g(1).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:Persimmon");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPersimmon, ecru_ItemPersimmon.class, "Persimmon");
        mod_ecru_MapleTree.blockDriedPersimmons = new ecru_BlockDriedPersimmon().func_149672_a(Block.field_149779_h);
        mod_ecru_MapleTree.blockDriedPersimmons.func_149711_c(0.2f).func_149663_c("mapletree:driedPersimmons").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockDriedPersimmons, ecru_ItemDriedPersimmons.class, "driedPersimmons");
        mod_ecru_MapleTree.blockCompost = new ecru_BlockCompost().func_149672_a(Block.field_149779_h);
        mod_ecru_MapleTree.blockCompost.func_149711_c(0.2f).func_149663_c("mapletree:compost").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCompost, ecru_ItemBlock.class, "Compost");
        mod_ecru_MapleTree.blockCauldron = new ecru_BlockCauldron();
        mod_ecru_MapleTree.blockCauldron.func_149711_c(1.0f).func_149672_a(Block.field_149769_e).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:SyrupCauldron");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCauldron, ecru_ItemCauldron.class, "ecru_BlockCauldron");
        mod_ecru_MapleTree.blockSpile = new ecru_BlockSpile().func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(0.1f).func_149663_c("mapletree:Spile").func_149672_a(Block.field_149769_e);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockSpile, ecru_ItemSpile.class, "ecru_BlockSpile");
        mod_ecru_MapleTree.blockPlanter = new ecru_BlockPlanter();
        mod_ecru_MapleTree.blockPlanter.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:Planter");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPlanter, ItemBlock.class, "ecru_BlockPlanter");
        mod_ecru_MapleTree.blockLighthouseIllumination = new ecru_BlockLighthouseIllumination();
        mod_ecru_MapleTree.blockLighthouseIllumination.func_149711_c(1.0f).func_149672_a(Block.field_149769_e).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:LighthouseIllumination");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockLighthouseIllumination, ItemBlock.class, "ecru_BlockLighthouseIllumination");
        mod_ecru_MapleTree.blockSLight = new ecru_BlockSLight();
        mod_ecru_MapleTree.blockSLight.func_149711_c(0.2f).func_149672_a(Block.field_149769_e).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:SLight");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockSLight, ecru_ItemSLight.class, "ecru_BlockSLight");
        mod_ecru_MapleTree.blockSLight2 = new ecru_BlockSLight2();
        mod_ecru_MapleTree.blockSLight2.func_149711_c(0.2f).func_149672_a(Block.field_149769_e).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:SLight2");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockSLight2, ecru_ItemSLight2.class, "ecru_BlockSLight2");
        mod_ecru_MapleTree.blockCookPot = new ecru_BlockCookPot().func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockCookPot.func_149711_c(2.0f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:CookPot");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCookPot, ItemBlock.class, "ecru_BlockCookPot");
        mod_ecru_MapleTree.blockStoneMortar = new ecru_BlockStoneMortar().func_149672_a(Block.field_149769_e).func_149663_c("mapletree:StoneMortar").func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(1.0f);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockStoneMortar, ItemBlock.class, "ecru_BlockStoneMortar");
        mod_ecru_MapleTree.blockEngine = new ecru_BlockEngine().func_149672_a(Block.field_149769_e).func_149663_c("mapletree:Engine").func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(1.0f);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockEngine, ItemBlock.class, "ecru_BlockEngine");
        mod_ecru_MapleTree.blockWhiteFence = new ecru_BlockWhiteFence().func_149672_a(Block.field_149766_f);
        mod_ecru_MapleTree.blockWhiteFence.func_149711_c(0.5f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:WhiteFence");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockWhiteFence, ecru_ItemWhiteFence.class, "ecru_BlockWhiteFence");
        mod_ecru_MapleTree.blockDecoration1 = new ecru_BlockDecoration1(mod_ecru_MapleTree.decoTextureID1).func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockDecoration1.func_149711_c(0.3f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149713_g(1).func_149663_c("mapletree:Decoration1");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockDecoration1, ecru_ItemDecoration1.class, "ecru_ItemDecoration1");
        mod_ecru_MapleTree.blockDecoration2 = new ecru_BlockDecoration2(mod_ecru_MapleTree.decoTextureID2).func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockDecoration2.func_149711_c(0.3f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149713_g(1).func_149663_c("mapletree:Decoration2");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockDecoration2, ecru_ItemDecoration2.class, "ecru_ItemDecoration2");
        mod_ecru_MapleTree.blockDecoration3 = new ecru_BlockDecoration3(mod_ecru_MapleTree.decoTextureID3).func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockDecoration3.func_149711_c(0.3f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149713_g(1).func_149663_c("mapletree:Decoration3");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockDecoration3, ecru_ItemDecoration3.class, "ecru_ItemDecoration3");
        mod_ecru_MapleTree.blockVanilla = new ecru_BlockVanilla().func_149672_a(Block.field_149766_f).func_149663_c("mapletree:Vanilla").func_149711_c(0.5f).func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockVanilla, ecru_ItemVanillaSplint.class, "ecru_ItemVanilla");
        mod_ecru_MapleTree.blockGrape = new ecru_BlockGrape().func_149672_a(Block.field_149766_f).func_149663_c("mapletree:Grape").func_149711_c(0.5f).func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockGrape, ecru_ItemGrapePergola.class, "ecru_ItemGrapePergola");
        mod_ecru_MapleTree.blockTomato = new ecru_BlockTomato().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Tomato").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockTomato, ItemBlock.class, "ecru_BlockTomato");
        mod_ecru_MapleTree.blockEggplant = new ecru_BlockEggplant().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Eggplant").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockEggplant, ItemBlock.class, "ecru_BlockEggplant");
        mod_ecru_MapleTree.blockOnion = new ecru_BlockOnion().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Onion").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockOnion, ItemBlock.class, "ecru_BlockOnion");
        mod_ecru_MapleTree.blockSprinkler = new ecru_BlockSprinkler().func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockSprinkler.func_149711_c(0.5f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:Sprinkler");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockSprinkler, ecru_ItemSprinkler.class, "ecru_BlockSprinkler");
        mod_ecru_MapleTree.blockJapaneseRadish = new ecru_BlockCropsJapaneseRadish().func_149663_c("mapletree:JapaneseRadish").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockJapaneseRadish, ItemBlock.class, "ecru_BlockCropsJapaneseRadish");
        mod_ecru_MapleTree.blockPepper = new ecru_BlockPepper().func_149663_c("mapletree:Pepper").func_149711_c(0.5f).func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPepper, ecru_ItemPepperSplint.class, "ecru_BlockPepper");
        mod_ecru_MapleTree.blockSpice = new ecru_BlockSpice().func_149663_c("mapletree:Spice").func_149711_c(0.5f).func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockSpice, ecru_ItemSpice.class, "ecru_BlockSpice");
        mod_ecru_MapleTree.blockFountain = new ecru_BlockFountain().func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockFountain.func_149711_c(0.5f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:Fountain");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockFountain, ecru_ItemFountain.class, "ecru_BlockFountain");
        mod_ecru_MapleTree.blockOreBlock = new ecru_BlockOreBlobk().func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockOreBlock.func_149711_c(5.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:Oreblock");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockOreBlock, ecru_ItemOreBlock.class, "ecru_BlockOreBlobk");
        mod_ecru_MapleTree.blockMiniStairs1 = new ecru_BlockMiniStairs(0).func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockMiniStairs1.func_149713_g(0).func_149711_c(0.2f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:MiniStairs1");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMiniStairs1, ecru_ItemMiniStairs1.class, "ecru_BlockMiniStairs0");
        mod_ecru_MapleTree.blockMiniStairs2 = new ecru_BlockMiniStairs(1).func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockMiniStairs2.func_149713_g(0).func_149711_c(0.2f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:MiniStairs2");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMiniStairs2, ecru_ItemMiniStairs2.class, "ecru_BlockMiniStairs1");
        mod_ecru_MapleTree.blockMiniStairs3 = new ecru_BlockMiniStairs(2).func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockMiniStairs3.func_149713_g(0).func_149711_c(0.2f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:MiniStairs3");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMiniStairs3, ecru_ItemMiniStairs3.class, "ecru_BlockMiniStairs2");
        mod_ecru_MapleTree.blockMiniStairs4 = new ecru_BlockMiniStairs(3).func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockMiniStairs4.func_149713_g(0).func_149711_c(0.2f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:MiniStairs4");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMiniStairs4, ecru_ItemMiniStairs4.class, "ecru_BlockMiniStairs3");
        mod_ecru_MapleTree.blockSunFlower = new ecru_BlockSunFlower().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:SunFlower").func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(0.3f);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockSunFlower, ecru_ItemSunFlower.class, "ecru_BlockSunFlower");
        mod_ecru_MapleTree.blockPetal = new ecru_BlockPetal();
        mod_ecru_MapleTree.blockPetal.func_149711_c(0.2f).func_149713_g(1).func_149672_a(Block.field_149779_h).func_149672_a(Block.field_149779_h).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:Petal");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPetal, ecru_ItemPetal.class, "ecru_BlockPetal");
        mod_ecru_MapleTree.blockOreFlowerRed = new ecru_BlockOreFlower().func_149647_a(mod_ecru_MapleTree.tabsMaple);
        mod_ecru_MapleTree.blockOreFlowerRed.func_149711_c(1.0f).func_149672_a(Block.field_149779_h).func_149663_c("mapletree:OreFlowerRed");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockOreFlowerRed, ecru_ItemOreFlowerRed.class, "ecru_BlockOreFlower");
        mod_ecru_MapleTree.blockOreFlowerIron = new ecru_BlockOreFlowerIron().func_149647_a(mod_ecru_MapleTree.tabsMaple);
        mod_ecru_MapleTree.blockOreFlowerIron.func_149711_c(1.0f).func_149672_a(Block.field_149779_h).func_149663_c("mapletree:OreFlowerIron");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockOreFlowerIron, ecru_ItemOreFlowerIron.class, "ecru_BlockOreFlowerIron");
        mod_ecru_MapleTree.blockOreFlowerGold = new ecru_BlockOreFlowerGold().func_149647_a(mod_ecru_MapleTree.tabsMaple);
        mod_ecru_MapleTree.blockOreFlowerGold.func_149711_c(1.0f).func_149672_a(Block.field_149779_h).func_149663_c("mapletree:OreFlowerGold");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockOreFlowerGold, ecru_ItemOreFlowerGold.class, "ecru_BlockOreFlowerGold");
        mod_ecru_MapleTree.blockOreFlowerMarble = new ecru_BlockOreFlowerMarble().func_149647_a(mod_ecru_MapleTree.tabsMaple);
        mod_ecru_MapleTree.blockOreFlowerMarble.func_149711_c(1.0f).func_149672_a(Block.field_149779_h).func_149663_c("mapletree:OreFlowerMarble");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockOreFlowerMarble, ecru_ItemOreFlowerMarble.class, "OreFlowerMarble");
        mod_ecru_MapleTree.blockAzuki = new ecru_BlockCropsAzuki().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Azuki");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockAzuki, ItemBlock.class, "ecru_BlockCropsAzuki");
        mod_ecru_MapleTree.blockStickyRiceCrops = new ecru_BlockCropsStickyRice().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:StickyRiceCrops");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockStickyRiceCrops, ItemBlock.class, "ecru_BlockCropsStickyRice");
        mod_ecru_MapleTree.blockRapeseed = new ecru_BlockCropsRapeseed().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Rapeseed");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockRapeseed, ItemBlock.class, "ecru_BlockCropsRapeseed");
        mod_ecru_MapleTree.blockChestnutsBurrs = new ecru_BlockChestnutsBurrs().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:ChestnutsBurrs").func_149711_c(0.2f).func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockChestnutsBurrs, ecru_ItemChestnutsBurrs.class, "ecru_BlockChestnutsBurrs");
        mod_ecru_MapleTree.blockCabbage = new ecru_BlockCropsCabbage().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Cabbage").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCabbage, ecru_ItemCabbage.class, "ecru_BlockCropsCabbage");
        mod_ecru_MapleTree.blockGrainHopper = new ecru_BlockGrainHopper();
        mod_ecru_MapleTree.blockGrainHopper.func_149711_c(1.0f).func_149672_a(Block.field_149769_e).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:GrainHopper");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockGrainHopper, ItemBlock.class, "ecru_BlockGrainHopper");
        mod_ecru_MapleTree.blockBiofuelPD = new ecru_BlockBiofuelPD().func_149672_a(Block.field_149769_e).func_149663_c("mapletree:BiofuelPD").func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(1.0f);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockBiofuelPD, ecru_ItemBiofuelPD.class, "ecru_BlockBiofuelPD");
        mod_ecru_MapleTree.blockHumanPowerDrive = new ecru_BlockHumanPowerDrive().func_149663_c("mapletree:HumanPowerDrive").func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(1.0f);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockHumanPowerDrive, ecru_ItemHumanPowerDrive.class, "ecru_BlockHumanPowerDrive");
        mod_ecru_MapleTree.blockPowerShaftGear = new ecru_BlockPowerShaftGear().func_149663_c("mapletree:PowerShaftGear").func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(0.3f);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPowerShaftGear, ecru_ItemPowerShaftGear.class, "ecru_BlockPowerShaftGear");
        mod_ecru_MapleTree.blockPowerShaft = new ecru_BlockPowerShaft().func_149663_c("mapletree:PowerShaft").func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(0.3f);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockPowerShaft, ecru_ItemPowerShaft.class, "ecru_BlockPowerShaft");
        mod_ecru_MapleTree.blockMarbleJewel0 = new ecru_BlockMarbleJewel(0);
        mod_ecru_MapleTree.blockMarbleJewel0.func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel0");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarbleJewel0, ecru_ItemMarbleJewel0.class, "ecru_ItemMarbleJewel0.class");
        mod_ecru_MapleTree.blockMarbleJewel1 = new ecru_BlockMarbleJewel(1);
        mod_ecru_MapleTree.blockMarbleJewel1.func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel1");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarbleJewel1, ecru_ItemMarbleJewel1.class, "ecru_ItemMarbleJewel1.class");
        mod_ecru_MapleTree.blockMarbleJewel2 = new ecru_BlockMarbleJewel(2);
        mod_ecru_MapleTree.blockMarbleJewel2.func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel2");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarbleJewel2, ecru_ItemMarbleJewel2.class, "ecru_ItemMarbleJewel2.class");
        mod_ecru_MapleTree.blockMarbleJewel3 = new ecru_BlockMarbleJewel(3);
        mod_ecru_MapleTree.blockMarbleJewel3.func_149715_a(0.4375f).func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel3");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarbleJewel3, ecru_ItemMarbleJewel3.class, "ecru_ItemMarbleJewel3.class");
        mod_ecru_MapleTree.blockMarbleJewel4 = new ecru_BlockMarbleJewel(4);
        mod_ecru_MapleTree.blockMarbleJewel4.func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel4");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarbleJewel4, ecru_ItemMarbleJewel4.class, "ecru_ItemMarbleJewel4.class");
        mod_ecru_MapleTree.blockMarbleJewel5 = new ecru_BlockMarbleJewel(5);
        mod_ecru_MapleTree.blockMarbleJewel5.func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel5");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarbleJewel5, ecru_ItemMarbleJewel5.class, "ecru_ItemMarbleJewel5.class");
        mod_ecru_MapleTree.blockMarbleJewel6 = new ecru_BlockMarbleJewel(6);
        mod_ecru_MapleTree.blockMarbleJewel6.func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel6");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarbleJewel6, ecru_ItemMarbleJewel6.class, "ecru_ItemMarbleJewel6.class");
        mod_ecru_MapleTree.blockMarbleJewel7 = new ecru_BlockMarbleJewel(7);
        mod_ecru_MapleTree.blockMarbleJewel7.func_149715_a(0.4375f).func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel7");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarbleJewel7, ecru_ItemMarbleJewel7.class, "ecru_ItemMarbleJewel7.class");
        mod_ecru_MapleTree.blockMarble = new ecru_BlockMarble();
        mod_ecru_MapleTree.blockMarble.func_149713_g(1).func_149711_c(1.0f).func_149752_b(10.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:DecorationJewel");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMarble, ecru_ItemMarble.class, "ecru_ItemMarble.class");
        mod_ecru_MapleTree.blockGrapeStompTub = new ecru_BlockGrapeTub();
        mod_ecru_MapleTree.blockGrapeStompTub.func_149711_c(1.0f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:GrapeStompTub");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockGrapeStompTub, ecru_ItemGrapeTub.class, "ecru_BlockGrapeTub");
        mod_ecru_MapleTree.blockWineBarrel = new ecru_BlockWineBarrel();
        mod_ecru_MapleTree.blockWineBarrel.func_149711_c(0.5f).func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149663_c("mapletree:WineBarrel");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockWineBarrel, ecru_ItemWineBarrel.class, "ecru_BlockWineBarrel");
        mod_ecru_MapleTree.blockWineFaucet = new ecru_BlockWineFaucet().func_149647_a(mod_ecru_MapleTree.tabsMaple).func_149711_c(0.1f).func_149663_c("mapletree:WineFaucet");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockWineFaucet, ecru_ItemWineFaucet.class, "ecru_BlockWineFaucet");
        mod_ecru_MapleTree.blockGatherItems = new ecru_BlockGatherItems();
        mod_ecru_MapleTree.blockGatherItems.func_149711_c(1.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:GatherItems");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockGatherItems, "GatherItems");
        mod_ecru_MapleTree.blockMortar = new ecru_BlockMortar().func_149672_a(Block.field_149769_e);
        mod_ecru_MapleTree.blockMortar.func_149711_c(2.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:Mortar");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockMortar, ecru_ItemMortar.class, "Mortar");
        mod_ecru_MapleTree.blockGrainDryer = new ecru_BlockGrainDryer();
        mod_ecru_MapleTree.blockGrainDryer.func_149711_c(1.0f).func_149672_a(Block.field_149769_e).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:GrainDryer");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockGrainDryer, "GrainDryer");
        mod_ecru_MapleTree.blockCropsCardamon = new ecru_BlockCropsCardamon().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Cardamon").func_149647_a(mod_ecru_MapleTree.tabsMapleCurry);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCropsCardamon, ItemBlock.class, "Cardamon");
        mod_ecru_MapleTree.blockCropsCumin = new ecru_BlockCropsCumin().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Cumin").func_149647_a(mod_ecru_MapleTree.tabsMapleCurry);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCropsCumin, ItemBlock.class, "Cumin");
        mod_ecru_MapleTree.blockCropsCoriander = new ecru_BlockCropsCoriander().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Coriander").func_149647_a(mod_ecru_MapleTree.tabsMapleCurry);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCropsCoriander, ItemBlock.class, "Coriander");
        mod_ecru_MapleTree.blockCropsTurmeric = new ecru_BlockCropsTurmeric().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Turmeric").func_149647_a(mod_ecru_MapleTree.tabsMapleCurry);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCropsTurmeric, ItemBlock.class, "Turmeric");
        mod_ecru_MapleTree.blockCropsFennel = new ecru_BlockCropsFennel().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Fennel").func_149647_a(mod_ecru_MapleTree.tabsMapleCurry);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCropsFennel, ItemBlock.class, "Fennel");
        mod_ecru_MapleTree.blockCropsChili_pepper = new ecru_BlockCropsChili_pepper().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Chili_pepper").func_149647_a(mod_ecru_MapleTree.tabsMapleCurry);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCropsChili_pepper, ItemBlock.class, "Chili_pepper");
        mod_ecru_MapleTree.blockAllspiceWood = new ecru_BlockAllspiceWood();
        mod_ecru_MapleTree.blockAllspiceWood.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:AllspiceWood");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockAllspiceWood, ecru_ItemAllspiceWood.class, "AllspiceWood");
        mod_ecru_MapleTree.blockCloveWood = new ecru_BlockCloveWood();
        mod_ecru_MapleTree.blockCloveWood.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:CloveWood");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCloveWood, ecru_ItemCloveWood.class, "CloveWood");
        mod_ecru_MapleTree.blockCinnamonWood = new ecru_BlockCinnamonWood();
        mod_ecru_MapleTree.blockCinnamonWood.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:CinnamonWood");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCinnamonWood, ecru_ItemCinnamonWood.class, "CinnamonWood");
        mod_ecru_MapleTree.blockStar_aniseWood = new ecru_BlockStar_aniseWood();
        mod_ecru_MapleTree.blockStar_aniseWood.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:Star_aniseWood");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockStar_aniseWood, ecru_ItemStar_aniseWood.class, "Star_aniseWood");
        mod_ecru_MapleTree.blockNutmegWood = new ecru_BlockNutmegWood();
        mod_ecru_MapleTree.blockNutmegWood.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:NutmegWood");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockNutmegWood, ecru_ItemNutmegWood.class, "NutmegWood");
        mod_ecru_MapleTree.blockAllSpiceLeaves = new ecru_BlockAllSpiceLeaves();
        mod_ecru_MapleTree.blockAllSpiceLeaves.func_149711_c(0.2f).func_149713_g(1).func_149672_a(Block.field_149779_h).func_149715_a(0.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:AllSpiceLeaves");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockAllSpiceLeaves, ecru_ItemAllSpiceLeaves.class, "AllSpiceLeaves");
        mod_ecru_MapleTree.blockCloveLeaves = new ecru_BlockCloveLeaves();
        mod_ecru_MapleTree.blockCloveLeaves.func_149711_c(0.2f).func_149713_g(1).func_149672_a(Block.field_149779_h).func_149715_a(0.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:CloveLeaves");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCloveLeaves, ecru_ItemCloveLeaves.class, "CloveLeaves");
        mod_ecru_MapleTree.blockCinnamonLeaves = new ecru_BlockCinnamonLeaves();
        mod_ecru_MapleTree.blockCinnamonLeaves.func_149711_c(0.2f).func_149713_g(1).func_149672_a(Block.field_149779_h).func_149715_a(0.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:CinnamonLeaves");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCinnamonLeaves, ecru_ItemCinnamonLeaves.class, "CinnamonLeaves");
        mod_ecru_MapleTree.blockStar_aniseLeaves = new ecru_BlockStar_aniseLeaves();
        mod_ecru_MapleTree.blockStar_aniseLeaves.func_149711_c(0.2f).func_149713_g(1).func_149672_a(Block.field_149779_h).func_149715_a(0.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:Star_aniseLeaves");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockStar_aniseLeaves, ecru_ItemStar_aniseLeaves.class, "Star_aniseLeaves");
        mod_ecru_MapleTree.blockNutmegLeaves = new ecru_BlockNutmegLeaves();
        mod_ecru_MapleTree.blockNutmegLeaves.func_149711_c(0.2f).func_149713_g(1).func_149672_a(Block.field_149779_h).func_149715_a(0.0f).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:NutmegLeaves");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockNutmegLeaves, ecru_ItemNutmegLeaves.class, "NutmegLeaves");
        mod_ecru_MapleTree.blockThinSapling = new ecru_BlockThinSapling().func_149672_a(Block.field_149779_h);
        mod_ecru_MapleTree.blockThinSapling.func_149711_c(0.2f).func_149713_g(1).func_149647_a(mod_ecru_MapleTree.tabsMapleCurry).func_149663_c("mapletree:ThinSapling");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockThinSapling, ecru_ItemThinSapling.class, "ThinSapling");
        mod_ecru_MapleTree.blockAllspiceThinPlanks = new ecru_BlockAllspiceThinPlanks();
        mod_ecru_MapleTree.blockAllspiceThinPlanks.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:AllspiceThinPlanks");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockAllspiceThinPlanks, ecru_ItemAllspiceThinPlanks.class, "AllspiceThinPlanks");
        mod_ecru_MapleTree.blockCinnamonThinPlanks = new ecru_BlockCinnamonThinPlanks();
        mod_ecru_MapleTree.blockCinnamonThinPlanks.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:CinnamonThinPlanks");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCinnamonThinPlanks, ecru_ItemCinnamonThinPlanks.class, "CinnamonThinPlanks");
        mod_ecru_MapleTree.blockCloveThinPlanks = new ecru_BlockCloveThinPlanks();
        mod_ecru_MapleTree.blockCloveThinPlanks.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:CloveThinPlanks");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockCloveThinPlanks, ecru_ItemCloveThinPlanks.class, "CloveThinPlanks");
        mod_ecru_MapleTree.blockNutmegThinPlanks = new ecru_BlockNutmegThinPlanks();
        mod_ecru_MapleTree.blockNutmegThinPlanks.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:NutmegThinPlanks");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockNutmegThinPlanks, ecru_ItemNutmegThinPlanks.class, "NutmegThinPlanks");
        mod_ecru_MapleTree.blockStarAniseThinPlanks = new ecru_BlockStarAniseThinPlanks();
        mod_ecru_MapleTree.blockStarAniseThinPlanks.func_149711_c(2.0f).func_149672_a(Block.field_149766_f).func_149647_a(mod_ecru_MapleTree.tabsMapleOther).func_149663_c("mapletree:StarAniseThinPlanks");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockStarAniseThinPlanks, ecru_ItemStarAniseThinPlanks.class, "StarAniseThinPlanks");
        mod_ecru_MapleTree.blockKelp = new ecru_BlockKelp().func_149672_a(Block.field_149779_h).func_149715_a(0.125f).func_149711_c(0.1f).func_149663_c("mapletree:Kelp");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockKelp, ItemBlock.class, "Kelp");
        mod_ecru_MapleTree.blockSunDryingNet = new ecru_BlockSunDryingNet().func_149672_a(Block.field_149769_e).func_149663_c("mapletree:SunDryingNet");
        mod_ecru_MapleTree.blockSunDryingNet.func_149711_c(0.5f);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockSunDryingNet, ItemBlock.class, "SunDryingNet");
        mod_ecru_MapleTree.blockTeuchiUdon = new ecru_BlockTeuchiUdon("udon", 0).func_149672_a(Block.field_149773_n).func_149711_c(50.0f).func_149713_g(0).func_149663_c("mapletree:TeuchiUdon").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockTeuchiUdon, ecru_ItemTeuchiUdon.class, "TeuchiUdon");
        mod_ecru_MapleTree.blockTeuchiSoba = new ecru_BlockTeuchiUdon("soba", 1).func_149672_a(Block.field_149773_n).func_149711_c(50.0f).func_149713_g(0).func_149663_c("mapletree:TeuchiSoba").func_149647_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockTeuchiSoba, ecru_ItemTeuchiSoba.class, "TeuchiSoba");
        mod_ecru_MapleTree.blockBuckwheat = new ecru_BlockCropsSoba().func_149672_a(Block.field_149779_h).func_149663_c("mapletree:Buckwheat");
        GameRegistry.registerBlock(mod_ecru_MapleTree.blockBuckwheat, ItemBlock.class, "Buckwheat");
    }
}
