package ecru.MapleTree;

import cpw.mods.fml.common.registry.GameRegistry;
import ecru.MapleTree.item.ecru_ItemAdd;
import ecru.MapleTree.item.ecru_ItemAlwaysFoods;
import ecru.MapleTree.item.ecru_ItemAxe;
import ecru.MapleTree.item.ecru_ItemBoiledBonito;
import ecru.MapleTree.item.ecru_ItemCurryRice;
import ecru.MapleTree.item.ecru_ItemCurryRoux;
import ecru.MapleTree.item.ecru_ItemCurrySpice;
import ecru.MapleTree.item.ecru_ItemFoodAdd;
import ecru.MapleTree.item.ecru_ItemFoods;
import ecru.MapleTree.item.ecru_ItemFoodstuff;
import ecru.MapleTree.item.ecru_ItemGacha;
import ecru.MapleTree.item.ecru_ItemHoe;
import ecru.MapleTree.item.ecru_ItemJewel;
import ecru.MapleTree.item.ecru_ItemKelpSporophyte;
import ecru.MapleTree.item.ecru_ItemMachinedBonito;
import ecru.MapleTree.item.ecru_ItemMapleSyrupPotion;
import ecru.MapleTree.item.ecru_ItemMomijiShears;
import ecru.MapleTree.item.ecru_ItemMushroom;
import ecru.MapleTree.item.ecru_ItemNormal;
import ecru.MapleTree.item.ecru_ItemParticle;
import ecru.MapleTree.item.ecru_ItemPickaxe;
import ecru.MapleTree.item.ecru_ItemRake;
import ecru.MapleTree.item.ecru_ItemReactivationChemicalAgents;
import ecru.MapleTree.item.ecru_ItemRiceSeeds;
import ecru.MapleTree.item.ecru_ItemSeeds;
import ecru.MapleTree.item.ecru_ItemSpade;
import ecru.MapleTree.item.ecru_ItemSpiceList;
import ecru.MapleTree.item.ecru_ItemStewCurry;
import ecru.MapleTree.item.ecru_ItemSunDryingBonito;
import ecru.MapleTree.item.ecru_ItemSunDryingCuttlefish;
import ecru.MapleTree.item.ecru_ItemSunDryingKelp;
import ecru.MapleTree.item.ecru_ItemSunFlowerSeeds;
import ecru.MapleTree.item.ecru_ItemSword;
import net.minecraft.init.Blocks;
import net.minecraft.potion.Potion;

public class mapleTreeRegistryItem {
    public void registry() {
        mod_ecru_MapleTree.Item_tabIcon = new ecru_ItemAdd("mapletree:tabIcon").func_77637_a(null).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_tabIcon, "tabIcon", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_tabIconCurry = new ecru_ItemAdd("mapletree:tabIconCurry").func_77637_a(null).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_tabIconCurry, "tabIconCurry", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_tabIconOther = new ecru_ItemAdd("mapletree:tabIconOther").func_77637_a(null).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_tabIconOther, "tabIconOther", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_particle = new ecru_ItemParticle().func_77655_b("mapletree:particle");
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_particle, "particle", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_tomatoSeeds = new ecru_ItemSeeds(mod_ecru_MapleTree.blockTomato, Blocks.field_150458_ak, "mapletree:tomatoSeed").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_tomatoSeeds, "tomatoSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_eggplantSeeds = new ecru_ItemSeeds(mod_ecru_MapleTree.blockEggplant, Blocks.field_150458_ak, "mapletree:eggplantSeed").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_eggplantSeeds, "eggplantSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_onionSeeds = new ecru_ItemSeeds(mod_ecru_MapleTree.blockOnion, Blocks.field_150458_ak, "mapletree:onionSeed").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_onionSeeds, "onionSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_grapeSeed = new ecru_ItemAdd("mapletree:grapeSeed").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_grapeSeed, "grapeSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_vanillaSeed = new ecru_ItemAdd("mapletree:vanillaSeed").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_vanillaSeed, "vanillaSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_AzukiBeans = new ecru_ItemSeeds(mod_ecru_MapleTree.blockAzuki, Blocks.field_150458_ak, "mapletree:azukiBeans");
        mod_ecru_MapleTree.Item_AzukiBeans.func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_AzukiBeans, "AzukiBeans", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_unhulledStickyRice = new ecru_ItemRiceSeeds(mod_ecru_MapleTree.blockStickyRiceCrops, Blocks.field_150458_ak, "mapletree:unhulledStickyRice");
        mod_ecru_MapleTree.Item_unhulledStickyRice.func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_unhulledStickyRice, "unhulledStickyRice", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_rapeSeeds = new ecru_ItemSeeds(mod_ecru_MapleTree.blockRapeseed, Blocks.field_150458_ak, "mapletree:rapeSeeds");
        mod_ecru_MapleTree.Item_rapeSeeds.func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_rapeSeeds, "rapeSeeds", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cabbageSeeds = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCabbage, Blocks.field_150458_ak, "mapletree:cabbageSeeds");
        mod_ecru_MapleTree.Item_cabbageSeeds.func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cabbageSeeds, "cabbageSeeds", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_SunFlowerSeed = new ecru_ItemSunFlowerSeeds().func_77655_b("mapletree:sunflowerSeed").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_SunFlowerSeed, "SunFlowerSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_japaneseRadishSeeds = new ecru_ItemSeeds(mod_ecru_MapleTree.blockJapaneseRadish, Blocks.field_150458_ak, "mapletree:japaneseRadishSeeds");
        mod_ecru_MapleTree.Item_japaneseRadishSeeds.func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_japaneseRadishSeeds, "japaneseRadishSeeds", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_buckwheatSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockBuckwheat, Blocks.field_150458_ak, "mapletree:buckwheatSeed");
        mod_ecru_MapleTree.Item_buckwheatSeed.func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_buckwheatSeed, "buckwheatSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_tomato = new ecru_ItemFoodAdd(1, 0.6f, false, "mapletree:tomato").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_tomato, "tomato", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_eggplant = new ecru_ItemFoodAdd(1, 0.6f, false, "mapletree:eggplant").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_eggplant, "eggplant", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_onion = new ecru_ItemFoodAdd(1, 0.6f, false, "mapletree:onion").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_onion, "onion", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_mapleChip = new ecru_ItemAdd("mapletree:mapleChip").func_77637_a(mod_ecru_MapleTree.tabsMapleOther).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_mapleChip, "mapleChip", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_mapleSyrup = new ecru_ItemFoodAdd(1, 0.6f, false, "mapletree:mapleSyrup").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_mapleSyrup, "mapleSyrup", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_hotCake = new ecru_ItemFoodAdd(10, 0.8f, false, "mapletree:hotCake").func_77637_a(mod_ecru_MapleTree.tabsMaple);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_hotCake, "hotCake", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_maplePudding = new ecru_ItemFoodAdd(8, 0.8f, false, "mapletree:maplePudding").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_maplePudding, "maplePudding", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_softCreamVanilla = new ecru_ItemFoodAdd(4, 0.6f, false, "mapletree:softCreamVanilla").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_softCreamVanilla, "softCreamVanilla", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_grape = new ecru_ItemFoodAdd(2, 0.6f, false, "mapletree:grape").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_grape, "grape", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_grapePoundCake = new ecru_ItemFoodAdd(6, 0.8f, false, "mapletree:grapePoundCake").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_grapePoundCake, "grapePoundCake", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_vanillaSheath = new ecru_ItemAdd("mapletree:vanillaSheath").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_vanillaSheath, "vanillaSheath", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_vanillaBeans = new ecru_ItemAdd("mapletree:vanillaBeans").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_vanillaBeans, "vanillaBeans", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_chestnut = new ecru_ItemAdd("mapletree:chestnut").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_chestnut, "chestnut", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_chestnutsBburrs = new ecru_ItemAdd("mapletree:chestnutsBburrs").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_chestnutsBburrs, "chestnutsBburrs", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_roastChestnuts = new ecru_ItemFoodAdd(4, 0.6f, false, "mapletree:roastChestnuts").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_roastChestnuts, "roastChestnuts", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_treeManure = new ecru_ItemAdd("mapletree:treeManure").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_treeManure, "treeManure", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_flour = new ecru_ItemAdd("mapletree:flour").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_flour, "flour", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_salt = new ecru_ItemAdd("mapletree:salt").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_salt, "salt", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_dough = new ecru_ItemAdd("mapletree:dough").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_dough, "dough", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_hamburger_meat = new ecru_ItemAdd("mapletree:hamburger_meat").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_hamburger_meat, "hamburger_meat", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_grilled_eggplant = new ecru_ItemFoodAdd(4, 0.6f, false, "mapletree:grilled_eggplant").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_grilled_eggplant, "grilled_eggplant", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_buns = new ecru_ItemFoodAdd(2, 0.6f, false, "mapletree:buns").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_buns, "buns", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_hamburger = new ecru_ItemFoodAdd(6, 0.8f, false, "mapletree:hamburger").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_hamburger, "hamburger", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cheese = new ecru_ItemFoodAdd(2, 0.6f, false, "mapletree:cheese").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cheese, "cheese", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cheeseBurger = new ecru_ItemFoodAdd(10, 0.8f, false, "mapletree:cheeseBurger", Potion.field_76432_h.field_76415_H, 1, 1).func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cheeseBurger, "cheeseBurger", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_ReactivationChemicalAgents = new ecru_ItemReactivationChemicalAgents().func_77655_b("mapletree:reactivationChemicalAgents").func_77637_a(mod_ecru_MapleTree.tabsMapleOther).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_ReactivationChemicalAgents, "reactivationChemicalAgents", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_kelpSporophyte = new ecru_ItemKelpSporophyte().func_77655_b("mapletree:kelpSporophyte").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_kelpSporophyte, "kelpSporophyte", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_machinedBonito = new ecru_ItemMachinedBonito("mapletree:machinedBonito").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(1);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_machinedBonito, "machinedBonito", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_BoiledBonito = new ecru_ItemBoiledBonito("mapletree:boiledBonito").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(1);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_BoiledBonito, "boiledBonito", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_sunDryingBonito = new ecru_ItemSunDryingBonito("mapletree:sunDryingBonito").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(1);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_sunDryingBonito, "sunDryingBonito", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_sunDryingCuttlefish = new ecru_ItemSunDryingCuttlefish("mapletree:sunDryingCuttlefish").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(1);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_sunDryingCuttlefish, "sunDryingCuttlefish", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_sunDryingKelp = new ecru_ItemSunDryingKelp("mapletree:sunDryingKelp").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(1);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_sunDryingKelp, "sunDryingKelp", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_foodstuff = new ecru_ItemFoodstuff("mapletree:foodstuff").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_foodstuff, "foodstuff", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_foodsDish = new ecru_ItemFoods("mapletree:foodsDish").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_foodsDish, "foodsDish", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_normalItem = new ecru_ItemNormal("mapletree:normalItem").func_77637_a(mod_ecru_MapleTree.tabsMapleOther).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_normalItem, "normalItem", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_alwaysFoods = new ecru_ItemAlwaysFoods("mapletree:alwaysFoods").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_alwaysFoods, "alwaysFoods", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_mushroom = new ecru_ItemMushroom("mapletree:mushroom").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_mushroom, "mushroom", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_SpiceList = new ecru_ItemSpiceList("mapletree:spiceList").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_SpiceList, "spices", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cardamonFruit = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCropsCardamon, Blocks.field_150458_ak, "mapletree:cardamonFruit").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cardamonFruit, "cardamonFruit", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cardamonSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCropsCardamon, Blocks.field_150458_ak, "mapletree:cardamonSeed").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cardamonSeed, "cardamonSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cuminSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCropsCumin, Blocks.field_150458_ak, "mapletree:cuminSeed").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cuminSeed, "cuminSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_corianderSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCropsCoriander, Blocks.field_150458_ak, "mapletree:corianderSeed").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_corianderSeed, "corianderSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_turmericRoot = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCropsTurmeric, Blocks.field_150458_ak, "mapletree:turmericRoot").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_turmericRoot, "turmericRoot", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_chili_pepperFruit = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCropsChili_pepper, Blocks.field_150458_ak, "mapletree:chili_pepperFruit").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_chili_pepperFruit, "chili_pepperFruit", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_chili_pepperSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCropsChili_pepper, Blocks.field_150458_ak, "mapletree:chili_pepperSeed").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_chili_pepperSeed, "chili_pepperSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_fennelSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockCropsFennel, Blocks.field_150458_ak, "mapletree:fennelSeed").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_fennelSeed, "fennelSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_allspiceSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockThinSapling, Blocks.field_150458_ak, "mapletree:allspiceSeed", 0).func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_allspiceSeed, "allspiceSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cloveBud = new ecru_ItemAdd("mapletree:cloveBud").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cloveBud, "cloveBud", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cloveFruit = new ecru_ItemSeeds(mod_ecru_MapleTree.blockThinSapling, Blocks.field_150458_ak, "mapletree:cloveFruit", 1).func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cloveFruit, "cloveFruit", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_star_aniseFruit = new ecru_ItemAdd("mapletree:star_aniseFruit").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_star_aniseFruit, "star_aniseFruit", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_nutmegFruit = new ecru_ItemAdd("mapletree:nutmegFruit").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_nutmegFruit, "nutmegFruit", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cinnamonFruit = new ecru_ItemSeeds(mod_ecru_MapleTree.blockThinSapling, Blocks.field_150458_ak, "mapletree:cinnamonFruit", 2).func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cinnamonFruit, "cinnamonFruit", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_cinnamonBark = new ecru_ItemAdd("mapletree:cinnamonBark").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_cinnamonBark, "cinnamonBark", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_nutmegSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockThinSapling, Blocks.field_150458_ak, "mapletree:nutmegSeed", 4).func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_nutmegSeed, "nutmegSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_star_aniseSeed = new ecru_ItemSeeds(mod_ecru_MapleTree.blockThinSapling, Blocks.field_150458_ak, "mapletree:star_aniseSeed", 3).func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_star_aniseSeed, "star_aniseSeed", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_Curryspice = new ecru_ItemCurrySpice("mapletree:currySpice").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_Curryspice, "currySpice", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_CurryRoux = new ecru_ItemCurryRoux("mapletree:curryRoux").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_CurryRoux, "curryRoux", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_StewCurry = new ecru_ItemStewCurry("mapletree:stewCurry").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_StewCurry, "stewCurry", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_CurryRice = new ecru_ItemCurryRice("mapletree:curryRice").func_77637_a(mod_ecru_MapleTree.tabsMapleCurry).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_CurryRice, "curryRice", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_jewelMapleDia = new ecru_ItemAdd("mapletree:mapleDiamondRepair").func_77637_a(mod_ecru_MapleTree.tabsMapleOther).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_jewelMapleDia, "mapleDiamondRepair", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_jewel = new ecru_ItemJewel().func_77637_a(mod_ecru_MapleTree.tabsMapleOther).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_jewel, "jewel", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_mapleSyrupPotion = new ecru_ItemMapleSyrupPotion().func_77655_b("mapletree:mapleSyrupPotion").func_77637_a(mod_ecru_MapleTree.tabsMaple).func_77625_d(12);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_mapleSyrupPotion, "mapleSyrupPotion", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_momijiShears = new ecru_ItemMomijiShears(238, "mapletree:momijiShears").func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_momijiShears, "momijiShears", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_momijiShearsMapleDiamond = new ecru_ItemMomijiShears(5000, "mapletree:momijiShearsMapleDiamond").func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_momijiShearsMapleDiamond, "momijiShearsMapleDiamond", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_rake = new ecru_ItemRake(200, "mapletree:rake", 0).func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_rake, "rake", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_rakeTallgrass = new ecru_ItemRake(200, "mapletree:rakeTallgrass", 1).func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_rakeTallgrass, "rakeTallgrass", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_gacha = new ecru_ItemGacha("mapletree:gacha").func_77637_a(mod_ecru_MapleTree.tabsMapleOther).func_77625_d(64);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_gacha, "gacha", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_fireproofRing = new ecru_ItemAdd("mapletree:fireproofRing").func_77637_a(mod_ecru_MapleTree.tabsMapleOther).func_77625_d(1);
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_fireproofRing, "fireproofRing", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_PickaxeMapleDiamond = new ecru_ItemPickaxe(mod_ecru_MapleTree.toolMaterialMapleDiamond).func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        mod_ecru_MapleTree.Item_PickaxeMapleDiamond.func_77655_b("mapletree:pickaxeMapleDiamond").func_111206_d("mapletree:pickaxeMapleDiamond");
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_PickaxeMapleDiamond, "PickaxeMapleDiamond", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_AxeMapleDiamond = new ecru_ItemAxe(mod_ecru_MapleTree.toolMaterialMapleDiamond).func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        mod_ecru_MapleTree.Item_AxeMapleDiamond.func_77655_b("mapletree:axeMapleDiamond").func_111206_d("mapletree:axeMapleDiamond");
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_AxeMapleDiamond, "AxeMapleDiamond", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_ShovelMapleDiamond = new ecru_ItemSpade(mod_ecru_MapleTree.toolMaterialMapleDiamond).func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        mod_ecru_MapleTree.Item_ShovelMapleDiamond.func_77655_b("mapletree:shovelMapleDiamond").func_111206_d("mapletree:shovelMapleDiamond");
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_ShovelMapleDiamond, "ShovelMapleDiamond", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_SwordMapleDiamond = new ecru_ItemSword(mod_ecru_MapleTree.toolMaterialMapleDiamond).func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        mod_ecru_MapleTree.Item_SwordMapleDiamond.func_77655_b("mapletree:swordMapleDiamond").func_111206_d("mapletree:swordMapleDiamond");
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_SwordMapleDiamond, "SwordMapleDiamond", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_HoeMapleDiamond = new ecru_ItemHoe(mod_ecru_MapleTree.toolMaterialMapleDiamond).func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        mod_ecru_MapleTree.Item_HoeMapleDiamond.func_77655_b("mapletree:hoeMapleDiamond").func_111206_d("mapletree:hoeMapleDiamond");
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_HoeMapleDiamond, "HoeMapleDiamond", mod_ecru_MapleTree.MODID_SET);
        mod_ecru_MapleTree.Item_NoodlesCutKnife = new ecru_ItemSword(mod_ecru_MapleTree.toolMaterialKnife).func_77637_a(mod_ecru_MapleTree.tabsMapleOther);
        mod_ecru_MapleTree.Item_NoodlesCutKnife.func_77655_b("mapletree:noodlesCutKnife").func_111206_d("mapletree:noodlesCutKnife");
        GameRegistry.registerItem(mod_ecru_MapleTree.Item_NoodlesCutKnife, "NoodlesCutKnife", mod_ecru_MapleTree.MODID_SET);
    }
}
